SELECT
  *
FROM
  "SALES"."RETAILS"."CAR_SALE"
LIMIT
  10;

  SELECT 
    SELLINGPRICE,
    MMR,
    COLOR,
    INTERIOR,
    SELLER,
    SALEDATE
FROM SALES.RETAILS.CAR_SALE
LIMIT 20;


 SELECT * FROM "RETAILS"."CAR_SALE_PROCESSED" ; 

 
 CREATE OR REPLACE VIEW "RETAILS"."CAR_SALE_PROCESSED" AS
SELECT
    *,
    1 AS UNITS_SOLD,
    SELLINGPRICE * 1 AS TOTAL_REVENUE,
    
    CASE 
        WHEN SELLINGPRICE > 0 AND MMR IS NOT NULL 
        THEN ROUND((SELLINGPRICE - MMR) / SELLINGPRICE * 100, 2)
        ELSE NULL
    END AS PROFIT_MARGIN,
    
    CASE 
        WHEN SELLINGPRICE <= 0 OR MMR IS NULL THEN 'N/A'
        WHEN (SELLINGPRICE - MMR) / SELLINGPRICE * 100 > 20 THEN 'HIGH MARGIN'
        WHEN (SELLINGPRICE - MMR) / SELLINGPRICE * 100 BETWEEN 10 AND 20 THEN 'MEDIUM MARGIN'
        ELSE 'LOW MARGIN'
    END AS MARGIN_TIER,
    
    -- Fixed: Use exact format for your date strings
    YEAR(TO_DATE(SALEDATE, 'DY MON DD YYYY HH24:MI:SS'))    AS SALE_YEAR,
    QUARTER(TO_DATE(SALEDATE, 'DY MON DD YYYY HH24:MI:SS')) AS SALE_QUARTER,
    MONTH(TO_DATE(SALEDATE, 'DY MON DD YYYY HH24:MI:SS'))   AS SALE_MONTH
FROM "RETAILS"."CAR_SALE"
WHERE SALEDATE IS NOT NULL
  AND MAKE IS NOT NULL
  AND MODEL IS NOT NULL
  AND SELLINGPRICE > 0;

  SELECT * FROM "RETAILS"."CAR_SALE_PROCESSED" ;
